<?php
/**
 * hub-inject-deadline.php
 *
 * Part of the Integration Hub — this endpoint plays the role of a PEER
 * SUBSYSTEM (Committee Management and Assignment System, in the given
 * ten-subsystem list) pushing a "please track this deadline" request
 * into our Deadline Tracking module. Everything else in this codebase
 * that creates deadlines is either internal (Sec. 54/56, computed or
 * auto-generated from our own events) or staff-entered manually — this
 * is the one deliberately built to demonstrate the INBOUND direction:
 * data arriving FROM a simulated outside system, not generated by us.
 *
 * Still entirely mocked — no real Committee Management system exists.
 * The point is to make that inbound arrow demonstrable, not to fake that
 * a live connection exists.
 */

require_once __DIR__ . '/../../includes/db.php';
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/csrf.php';
require_once __DIR__ . '/../../includes/audit.php';

$user = requireApiAuth();
requireCsrfToken();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    jsonError('Method not allowed.', 405);
}

$b = getJsonBody();
$relatedItem = trim($b['related_item_id'] ?? '');
$label       = trim($b['label'] ?? '');
$dueDate     = $b['due_date'] ?? '';
$sourceSystem = trim($b['source_system'] ?? '') ?: 'Committee Management and Assignment System (simulated)';
$assignedToId = isset($b['assigned_to']) && $b['assigned_to'] !== '' ? (int) $b['assigned_to'] : null;

if ($relatedItem === '' || !DateTime::createFromFormat('Y-m-d', $dueDate)) {
    jsonError('related_item_id and a valid due_date are required.', 422);
}

$db = getDb();
$check = $db->prepare('SELECT id, title FROM agenda_items WHERE id = :id AND is_archived = 0');
$check->execute([':id' => $relatedItem]);
$item = $check->fetch();
if (!$item) {
    jsonError('Agenda item not found.', 404);
}

// ASSIGNMENT: resolve+validate the assignee now (not at read time), so a
// deactivated/deleted account can't silently become the "owner" of a
// deadline nobody can then complete except an admin.
$assignedToName = null;
if ($assignedToId !== null) {
    $userCheck = $db->prepare('SELECT id, full_name FROM users WHERE id = :id AND is_active = 1');
    $userCheck->execute([':id' => $assignedToId]);
    $assignee = $userCheck->fetch();
    if (!$assignee) {
        jsonError('The selected assignee was not found or is no longer active.', 422);
    }
    $assignedToName = $assignee['full_name'];
}

if ($label === '') {
    $label = "Committee report due — {$item['title']}";
}

$deadlineId = 'DL-' . strtoupper(bin2hex(random_bytes(3)));
$reason = "Requested by $sourceSystem via the Integration Hub — not generated by our own system."
    . ($assignedToName ? " Assigned to $assignedToName." : '');

$db->beginTransaction();
try {
    $db->prepare(
        "INSERT INTO deadlines (id, label, related_item_id, deadline_type, due_date, status, is_statutory, auto_generated, generation_reason, source_system, assigned_to_user_id, assigned_to_name)
         VALUES (:id, :label, :item, 'Committee Report', :due, 'Scheduled', 0, 1, :reason, :source, :assigned_id, :assigned_name)"
    )->execute([
        ':id'            => $deadlineId,
        ':label'         => $label,
        ':item'          => $relatedItem,
        ':due'           => $dueDate,
        ':reason'        => $reason,
        ':source'        => $sourceSystem,
        ':assigned_id'   => $assignedToId,
        ':assigned_name' => $assignedToName,
    ]);

    $db->prepare(
        "INSERT INTO integration_events (direction, event_type, related_session_id, summary, payload)
         VALUES ('inbound', 'deadline_request_received', NULL, :summary, :payload)"
    )->execute([
        ':summary' => "Received a deadline-tracking request from $sourceSystem for $relatedItem, due " . date('M j, Y', strtotime($dueDate)) . ($assignedToName ? ", assigned to $assignedToName" : '') . ".",
        ':payload' => json_encode(['deadline_id' => $deadlineId, 'related_item_id' => $relatedItem, 'due_date' => $dueDate, 'source_system' => $sourceSystem, 'assigned_to' => $assignedToName]),
    ]);

    $db->commit();
} catch (Exception $e) {
    $db->rollBack();
    error_log('Failed to inject hub deadline: ' . $e->getMessage());
    jsonError('Failed to save. Please try again.', 500);
}

logAudit('hub_inject_deadline', 'deadline', $deadlineId, "Simulated request from $sourceSystem, triggered by {$user['full_name']}" . ($assignedToName ? ", assigned to $assignedToName" : ''));

jsonSuccess(['id' => $deadlineId, 'assigned_to_name' => $assignedToName]);
