<?php
/**
 * ai_priority.php — calls the cloud-based LLM (Groq) to generate a ranked
 * priority suggestion for a pending agenda item. This is the ONLY file
 * that talks to the external AI API — kept isolated on purpose (see
 * Chapter 3, "Isolation of the AI Integration as a Bounded Component"),
 * so a failure or provider change here can't silently break unrelated
 * modules like Deadline Tracking.
 *
 * The output is always a SUGGESTION. Nothing in this file writes to
 * confirmed_priority — only api/agenda-items/confirm-priority.php does
 * that, and only in response to an explicit staff/councilor action. This
 * mirrors the human-in-the-loop design discussed in Chapter 2.
 */

require_once __DIR__ . '/config.php';

/**
 * DEBUG FEATURE: writes the raw prompt + Groq HTTP response to
 * includes/debug_last_ai_response.php as a comment block, overwritten on
 * every call. This is a SEPARATE file from this one on purpose — writing
 * runtime debug output into the actual file being executed on every
 * request would risk corrupting it under concurrent requests and would
 * make version control noisy. The debug file itself is never require()'d
 * or executed by anything; it exists purely so you can open it in your
 * editor and see exactly what the last AI call returned, without digging
 * through server logs or the database.
 */
function logRawAIResponse(array $item, string $prompt, string $rawHttpResponse, int $httpCode): void {
    $pretty = json_encode(json_decode($rawHttpResponse, true), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) ?: $rawHttpResponse;
    $timestamp = date('Y-m-d H:i:s');

    $content = "<?php\n"
        . "/**\n"
        . " * DEBUG FILE — auto-generated by includes/ai_priority.php, overwritten on\n"
        . " * every AI priority-suggestion call. Never required/executed by the app —\n"
        . " * safe to delete, will be recreated on the next call. Purely so you can\n"
        . " * open this file directly and see what Groq actually returned last time.\n"
        . " *\n"
        . " * Item:        {$item['id']}\n"
        . " * Called at:   $timestamp\n"
        . " * HTTP status: $httpCode\n"
        . " *\n"
        . " * --- Prompt sent ---\n"
        . " * " . str_replace("\n", "\n * ", $prompt) . "\n"
        . " *\n"
        . " * --- Raw HTTP response body from Groq ---\n"
        . " * " . str_replace("\n", "\n * ", $pretty) . "\n"
        . " */\n";

    file_put_contents(__DIR__ . '/debug_last_ai_response.php', $content);
}

function getAIPrioritySuggestion(array $item): array {
    $daysSinceFiled = (int) floor((strtotime('today') - strtotime($item['date_filed'])) / 86400);

    $prompt = "You are assisting a Philippine city council's legislative staff in triaging a pending "
        . "ordinance or resolution. Based ONLY on the details below, suggest a priority level "
        . "(High, Medium, or Low).\n\n"
        . "Title: {$item['title']}\n"
        . "Type: {$item['item_type']}\n"
        . "Category: {$item['category']}\n"
        . "Committee: {$item['committee']}\n"
        . "Date filed: {$item['date_filed']}\n"
        . "Days since filed: {$daysSinceFiled}\n\n"
        . "Guidance (not a rule to recite back): Emergency and Budget category measures usually "
        . "warrant High priority, but your reasoning must explain WHY this specific item is "
        . "time-sensitive or consequential — not just name its category. Let the title inform this: "
        . "a title referencing disaster response, public safety, or a hard deadline reads differently "
        . "than a routine renaming or administrative housekeeping measure, even within the same "
        . "category. Consider things like: what plausibly goes wrong if this measure sits for another "
        . "1-2 weeks given its actual subject and committee, whether {$daysSinceFiled} days pending is "
        . "fast or slow for a measure like this, and what the committee (\"{$item['committee']}\") "
        . "suggests about the kind of impact involved. If nothing about the item stands out as urgent, "
        . "say so plainly and justify Medium or Low on that basis instead of defaulting to Medium as a "
        . "non-answer.\n\n"
        . "Write reasoning as 1-2 sentences of actual analysis referencing the specific measure, not a "
        . "restatement of the category or priority level. Do NOT write sentences like \"X category, so "
        . "priority is Y\" or \"no urgent concerns\" without saying what you checked for and ruled out.\n\n"
        . "Respond ONLY in this exact JSON format, no extra text:\n"
        . '{"priority": "High|Medium|Low", "reasoning": "1-2 sentences of specific analysis"}';

    if (GROQ_API_KEY === 'PASTE_YOUR_GROQ_KEY_HERE' || GROQ_API_KEY === '') {
        return [
            'priority'  => null,
            'reasoning' => 'AI suggestion unavailable — no Groq API key configured in includes/config.php.',
            'error'     => true,
        ];
    }

    $ch = curl_init('https://api.groq.com/openai/v1/chat/completions');
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST           => true,
        CURLOPT_HTTPHEADER     => [
            'Authorization: Bearer ' . GROQ_API_KEY,
            'Content-Type: application/json',
        ],
        CURLOPT_POSTFIELDS => json_encode([
            'model'           => GROQ_MODEL,
            'messages'        => [['role' => 'user', 'content' => $prompt]],
            'response_format' => ['type' => 'json_object'],
            'temperature'     => 0.4,
        ]),
        CURLOPT_TIMEOUT => 15,
    ]);

    $response  = curl_exec($ch);
    $httpCode  = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $curlError = curl_error($ch);
    curl_close($ch);

    if ($response) {
        logRawAIResponse($item, $prompt, $response, $httpCode);
    }

    if ($curlError || !$response) {
        error_log('Groq API call failed: ' . $curlError);
        return [
            'priority'  => null,
            'reasoning' => 'AI suggestion unavailable — please assess manually.',
            'error'     => true,
        ];
    }

    $data = json_decode($response, true);

    if ($httpCode !== 200) {
        $errMsg = $data['error']['message'] ?? 'Unknown error';
        error_log("Groq API returned HTTP $httpCode: $errMsg");
        return [
            'priority'  => null,
            'reasoning' => 'AI suggestion unavailable — please assess manually.',
            'error'     => true,
        ];
    }

    $content = $data['choices'][0]['message']['content'] ?? '{}';
    $result  = json_decode($content, true);

    $priority = $result['priority'] ?? null;
    if (!in_array($priority, ['High', 'Medium', 'Low'], true)) {
        // Model returned something outside the expected set — treat as a
        // failure rather than silently writing a bad value to the DB.
        return [
            'priority'  => null,
            'reasoning' => 'AI returned an unexpected response — please assess manually.',
            'error'     => true,
        ];
    }

    return [
        'priority'  => $priority,
        'reasoning' => $result['reasoning'] ?? 'No reasoning returned.',
        'error'     => false,
    ];
}
